version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - DEBUG=false
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    environment:
      - USERNAME=kek
      - PASSWORD=kek
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./nginx/401.html:/etc/nginx/html/401.html
    depends_on:
      - backend
    networks:
      - app-network
    command: >
      /bin/sh -c "apk add --no-cache apache2-utils &&
                  htpasswd -b /etc/nginx/.htpasswd $$USERNAME $$PASSWORD &&
                  nginx -g 'daemon off;'"


networks:
  app-network:
    driver: bridge 